#define __SECRET_WS__ "REDACTED"
#define __SECRET_CONFIG_PASSWORD__ "REDACTED"

#define __SECRET_DISCORD_TOKEN__ "REDACTED"

#define __SECRET_PUSHOVER_USER__ "REDACTED"
#define __SECRET_PUSHOVER_APP__ "REDACTED"